/*
 * OpenAPI Polymorphism Test App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xyz.openapi.thinclient.api;

import com.xyz.openapi.thinclient.model.Animal;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for AnimalControllerApi
 */
@Ignore
public class AnimalControllerApiTest {

    private final AnimalControllerApi api = new AnimalControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAnimalsByTypeTest() {
        String animalType = null;
        List<Animal> response = api.getAnimalsByType(animalType);

        // TODO: test validations
    }
    
}
