/*
 * OpenAPI Polymorphism Test App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xyz.openapi.thinclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CatAllOf
 */
public class CatAllOfTest {
    private final CatAllOf model = new CatAllOf();

    /**
     * Model tests for CatAllOf
     */
    @Test
    public void testCatAllOf() {
        // TODO: test CatAllOf
    }

    /**
     * Test the property 'pawCount'
     */
    @Test
    public void pawCountTest() {
        // TODO: test pawCount
    }

}
