/*
 * OpenAPI Sample App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xyz.openapi.thinclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractEmployeeAllOf
 */
public class ContractEmployeeAllOfTest {
    private final ContractEmployeeAllOf model = new ContractEmployeeAllOf();

    /**
     * Model tests for ContractEmployeeAllOf
     */
    @Test
    public void testContractEmployeeAllOf() {
        // TODO: test ContractEmployeeAllOf
    }

    /**
     * Test the property 'vendorId'
     */
    @Test
    public void vendorIdTest() {
        // TODO: test vendorId
    }

    /**
     * Test the property 'vendorName'
     */
    @Test
    public void vendorNameTest() {
        // TODO: test vendorName
    }

}
