/*
 * OpenAPI Sample App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xyz.openapi.thinclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.xyz.openapi.thinclient.model.ContractEmployeeAllOf;
import com.xyz.openapi.thinclient.model.Department;
import com.xyz.openapi.thinclient.model.Employee;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractEmployee
 */
public class ContractEmployeeTest {
    private final ContractEmployee model = new ContractEmployee();

    /**
     * Model tests for ContractEmployee
     */
    @Test
    public void testContractEmployee() {
        // TODO: test ContractEmployee
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'atClass'
     */
    @Test
    public void atClassTest() {
        // TODO: test atClass
    }

    /**
     * Test the property 'vendorId'
     */
    @Test
    public void vendorIdTest() {
        // TODO: test vendorId
    }

    /**
     * Test the property 'vendorName'
     */
    @Test
    public void vendorNameTest() {
        // TODO: test vendorName
    }

}
